service: PedirPizzasProyecto

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  environment:
    REGION: ${self:provider.region}
    PENDING_ORDER_QUEUE: 
      Ref: PendingOrdersQueue 
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: "arn:aws:sqs:${self:provider.region}:*:PendingOrdersQueue"

functions:
  hacerPedido:
    handler: handler.hacerPedidoPizza
    events:
      - http:
          method: post
          path: pedido

resources:
  Resources:
    PendingOrdersQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "PendingOrdersQueue"
        
