service: PedirPizzasProyecto

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  environment:
    REGION: ${self:provider.region}
    PENDING_ORDER_QUEUE: 
      Ref: PendingOrdersQueue
    PENDING_ORDER_QUEUE_NAME: PendingOrdersQueue  
    PENDING_ORDER_QUEUE_URL: http://localhost:4566/queue/PendingOrdersQueue

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: 
        Fn::GetAtt:
        - PendingOrdersQueue
        - Arn
functions:
  hacerPedido:
    handler: handler.hacerPedidoPizza
    events:
      - http:
          method: post
          path: pedido
  prepararPedido: #Lambda que se va a activar cuando hay 
                  #nuevo mensaje en la cola SQS
    handler: handler.prepararPedidoPizza
    events: 
      - sqs:
          arn: #amazon resources name
            Fn::GetAtt:
              - PendingOrdersQueue #mismo recurso creado abajo 
              - Arn
          batchSize: 1 #cantidad de mensajes que esperamos 
                       #para disparar esta lambda
                       #En nuestro caso queremos preparar los pedidos 
                       #a medida que van llegando los mensajes uno por uno

resources:
  Resources:
    PendingOrdersQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:provider.environment.PENDING_ORDER_QUEUE_NAME}
        
